#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

$HOME/.config/polybar/hack/launch.sh

bspc monitor -d I II III IV V

feh --bg-center ~/home/mao/Downloads/1.jpg  

bspc config border_width         1
bspc config window_gap          12

bspc config focused_border_color "#ffffff"
bspc config normal_border_color "#575268"
bspc config active_border_color "#ffffff"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config presel_feedback true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

bspc rule -a Zathura state=tiled
bspc rule -a Nemo desktop='^1' follow=on focus=on; 
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a Navegador Mullvad desktop='^2' follow=on focus=on
bspc rule -a Lxappearance desktop='^3' follow=on focus=on
bspc rule -a Spotify desktop='^3' follow=on focus=on
bspc rule -a LibreWolf desktop='^2' follow=on focus=on
bspc rule -a qutebrowser desktop='^2' follow=on focus=on
bspc rule -a kitty desktop='^5' follow=on focus=on
bspc rule -a ranger desktop='^5' follow=on focus=on;
bspc rule -a Soffice desktop='^4'  follow=on focus=on
bspc rule -a sioyek desktop= '^4' follow=on focus=on

# Lauch xsettingsd daemon
xsettingsd --config="$BSPDIR"/xsettingsd &

# Autostart apps

conky &

# Start bspwm scripts

bspfloat
bspterm
bspwinmask &


# Fix cursor
xsetroot -cursor_name left_ptr

# Set wallpaper
#----------------------------

feh --bg-scale ~/.config/bspwm/wallpaper/3.jpg

pkill xautolock
xautolock -time 4 -locker "betterlockscreen -l" -notify 10 -notifier "notify-send 'Locker' 'Locking screen in 20 seconds'" -killtime 5 -killer "systemctl suspend" &

