#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

$HOME/.config/polybar/hack/launch.sh

bspc monitor -d I II III IV V VI

bspc config border_width 2
bspc config window_gap 12

bspc config focused_border_color "#ffffff"
bspc config normal_border_color "#575268"
bspc config active_border_color "#ffffff"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config presel_feedback true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

bspc rule -a Zathura desktop='^4' state=tiled follow=on focus=on
bspc rule -a Nemo desktop='^1' follow=on focus=on
bspc rule -a Brave-browser desktop='^2' follow=on focus=on
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a LibreWolf desktop='^2' follow=on focus=on
bspc rule -a qutebrowser desktop='^2' follow=on focus=on
bspc rule -a Lxappearance desktop='^3' follow=on focus=on
bspc rule -a calcurse desktop= '^5'follow=on focus=on
bspc rule -a Soffice desktop='^3' follow=on focus=on
bspc rule -a kitty desktop='^5' follow=on focus=on
bspc rule -a ncmpcpp desktop='^6' state=floating follow=off focus=on \ rectangle=800x600+580+400
bspc rule -a kew desktop='^6' state=floating follow=off focus=on \ rectangle=600x500+600+x600
bspc rule -a otter-launcher='^6' state=floating follow=off focus=on \ rectangle=800x600+580+400

# Autostart apps
pgrep -f mpd-notify.sh || ~/.local/bin/mpd-notify.sh &
pgrep -x dunst || dunst &
conky &

###feh --bg-fill /home/mao/

# Fix cursor
xsetroot -cursor_name left_ptr

pkill xautolock
xautolock -time 2 -locker "betterlockscreen -l" -notify 30 -notifier "notify-send 'Locker' 'Locking screen in 30 seconds'" -killtime 5 -killer "systemctl suspend" &
